### ISSUE TITLE
Get Test and Deploy to work in Jenkins on DerekNode

### ISSUE THREAD

**Issue by muttlake** [1803-mar12-net/proj2-derek-joseph-tim#5]

**Comment by muttlake** [comment]
Deploy data service to Default Web Site/DataSvc
Deploy lib service to Default Web Site/LibSvc
Deploy clientmvc to Default Web Site/WeatherApp

**Comment by Kamakani** [comment]
What do you mean by deploy them?

**Comment by Kamakani** [comment]
Do you mean change all of the hard coded links in the app to point to those destinations?

**Comment by muttlake** [comment]
I just mean we have to get it to work where after Jenkins finishes a build
on Derek node the weather app works with services

**Comment by muttlake** [comment]
Yeah you would have to change the hardcover urls

**Comment by Kamakani** [comment]
ok. Ill work on that now. when I'm done I'll probably study the rest of the night.

**Comment by muttlake** [comment]
It's cool. I just put it as an issue in girhub. I didn't know it was going
to send us emails

**Comment by muttlake** [comment]
We got this to work

Closing
